"""
Django settings for GeniAnalysis project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'GeniAnalysis.settings')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_1w10e8$4pau=!&t2-^0n^2zg^#arbdt4+%lt74ewa344eal#$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
	'channels',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'GeniAnalysis_app',
	'django_crontab',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GeniAnalysis.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

# WSGI_APPLICATION = 'GeniAnalysis.wsgi.application'

ASGI_APPLICATION = 'GeniAnalysis.asgi.application'

# ASGI_APPLICATION = "GeniAnalysis.GeniAnalysis_app.routing.application"

# SWEETIFY_SWEETALERT_LIBRARY = 'sweetalert'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
	'default': {
				'ENGINE': 'django.db.backends.mysql',
				'NAME': 'genianalysis_db',
				# 'NAME': 'GeniAnalysis_DB',
				'USER': 'root',
				'PORT': '3306',
				'PASSWORD':'',
				'HOST': 'localhost',
	}
}

CHANNEL_LAYERS = {
	'default':{
		"BACKEND": "channels.layers.InMemoryChannelLayer",
	}
}

# CHANNEL_LAYERS = {
	# "default": {
		# "BACKEND": "channels_redis.core.RedisChannelLayer",
		# "CONFIG": {
			 # "hosts": [('172.105.57.86', 6379)],
		# },
	# },
# }


CRONJOBS = [
	('* * * * *', 'GeniAnalysis_app.cron.my_cron_job')
]


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_ROOT = os.path.join(BASE_DIR, 'static/')


STATICFILES_DIRS = (
	os.path.join(BASE_DIR, "static"),
)

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


##############################################
CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = ['https://genianalysis.com']

############################## Email Settings ##############

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.office365.com'
# EMAIL_HOST_USER = 'support@genianalysis.com'
# EMAIL_HOST_PASSWORD = '9311679353' 
# EMAIL_PORT = 587 
# EMAIL_USE_TLS = True	  

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtpout.secureserver.net'
EMAIL_HOST_USER = 'support@genianalysis.com'
EMAIL_HOST_PASSWORD = '9311679353' 
EMAIL_PORT = 587 
EMAIL_USE_TLS = True

#################### File Handling ####################

CONTENT_TYPES = ['image', 'video']
MAX_UPLOAD_SIZE = "5242880"