# Generated by Django 4.0.1 on 2022-02-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_user_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_time', models.TimeField(auto_now=True)),
                ('today_date', models.DateField(auto_now=True)),
                ('strike_price', models.CharField(blank=True, max_length=100, null=True)),
                ('call_change_oi', models.CharField(blank=True, max_length=100, null=True)),
                ('put_change_oi', models.CharField(blank=True, max_length=100, null=True)),
                ('ltp', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryLogInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('user_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='TestingTime',
        ),
        migrations.AddField(
            model_name='historyloginterval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeniAnalysis_app.userdetails'),
        ),
    ]
