# Generated by Django 4.0.1 on 2022-02-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0002_adminuser_historylog_historyloginterval_userdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumOfOiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_time', models.TimeField(auto_now=True)),
                ('today_date', models.DateField(auto_now=True)),
                ('total_call_change_oi', models.CharField(blank=True, max_length=100, null=True)),
                ('total_put_change_oi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
