# Generated by Django 4.0.1 on 2022-02-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0003_sumofoilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyloginterval',
            name='interval_total_oi',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
