# Generated by Django 4.0.1 on 2022-02-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0004_historyloginterval_interval_total_oi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveOpenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateField(auto_now=True)),
                ('open_val', models.CharField(max_length=100)),
            ],
        ),
    ]
