# Generated by Django 4.0.1 on 2022-02-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0006_userdetails_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='approval_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
