# Generated by Django 4.0.1 on 2022-02-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0008_userdetails_is_login_userdetails_login_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastOptionChainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateField(auto_now=True)),
                ('call_oi', models.CharField(max_length=50)),
                ('call_change_oi', models.CharField(max_length=50)),
                ('call_volume', models.CharField(max_length=50)),
                ('call_price_change', models.CharField(max_length=50)),
                ('call_ltp', models.CharField(max_length=50)),
                ('strike_price', models.CharField(max_length=50)),
                ('put_ltp', models.CharField(max_length=50)),
                ('put_price_change', models.CharField(max_length=50)),
                ('put_volume', models.CharField(max_length=50)),
                ('put_change_oi', models.CharField(max_length=50)),
                ('put_oi', models.CharField(max_length=50)),
            ],
        ),
    ]
