# Generated by Django 4.0.1 on 2022-02-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0010_bankniftyhistoryloginterval'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnfHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_time', models.TimeField(auto_now=True)),
                ('today_date', models.DateField(auto_now=True)),
                ('strike_price', models.CharField(blank=True, max_length=100, null=True)),
                ('call_change_oi', models.CharField(blank=True, max_length=100, null=True)),
                ('put_change_oi', models.CharField(blank=True, max_length=100, null=True)),
                ('ltp', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BnfSaveOpenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateField(auto_now=True)),
                ('open_val', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BnfSumOfOiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_time', models.TimeField(auto_now=True)),
                ('today_date', models.DateField(auto_now=True)),
                ('total_call_change_oi', models.CharField(blank=True, max_length=100, null=True)),
                ('total_put_change_oi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
