# Generated by Django 4.0.1 on 2022-02-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0011_bnfhistorylog_bnfsaveopenmodel_bnfsumofoilog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnfGannHighLow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateField(auto_now=True)),
                ('high_val', models.CharField(max_length=100)),
                ('low_val', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GannHighLow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateField(auto_now=True)),
                ('high_val', models.CharField(max_length=100)),
                ('low_val', models.CharField(max_length=100)),
            ],
        ),
    ]
