# Generated by Django 4.0.1 on 2022-02-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0012_bnfgannhighlow_gannhighlow'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiftySentiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fil', models.CharField(max_length=10)),
                ('oi', models.CharField(max_length=10)),
                ('sgx', models.CharField(max_length=10)),
                ('preop', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeniAnalysis_app.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='BankNiftySentiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fil', models.CharField(max_length=10)),
                ('oi', models.CharField(max_length=10)),
                ('sgx', models.CharField(max_length=10)),
                ('preop', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeniAnalysis_app.userdetails')),
            ],
        ),
    ]
