# Generated by Django 4.0.1 on 2022-03-07 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0014_alter_bankniftysentiments_fil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('discount', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('payble_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('best_value', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
                ('receipt', models.FileField(upload_to='sub_receipt/')),
                ('fk_subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeniAnalysis_app.subscription_plan')),
            ],
        ),
        migrations.DeleteModel(
            name='LastOptionChainRecord',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeniAnalysis_app.userdetails'),
        ),
    ]
