# Generated by Django 4.0.1 on 2022-03-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0016_subscription_plan_extra_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='login_user_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
