# Generated by Django 4.0.1 on 2022-03-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0017_adminuser_login_user_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeniModeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genimode_status', models.IntegerField()),
                ('genimode_type', models.CharField(blank=True, max_length=100, null=True)),
                ('genimode_strike_price', models.CharField(blank=True, max_length=100, null=True)),
                ('genimode_current_ltp', models.CharField(blank=True, max_length=100, null=True)),
                ('genimode_target', models.CharField(blank=True, max_length=100, null=True)),
                ('genimode_stop_loss', models.CharField(blank=True, max_length=100, null=True)),
                ('today_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
