# Generated by Django 4.0.1 on 2022-03-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0018_genimodedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='genimodedetails',
            name='symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
