# Generated by Django 4.0.1 on 2022-03-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0023_transaction_end_date_transaction_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan',
            name='subscription_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
