# Generated by Django 4.0.1 on 2022-03-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0024_subscription_plan_subscription_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan',
            name='gst_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
