# Generated by Django 4.0.3 on 2022-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0026_transaction_cf_order_id_transaction_order_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan',
            name='net_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
