# Generated by Django 4.0.1 on 2022-03-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0027_subscription_plan_net_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAndResistence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_price', models.CharField(blank=True, max_length=100, null=True)),
                ('analysis', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeniAnalysis_app.userdetails')),
            ],
        ),
    ]
