# Generated by Django 4.0.1 on 2022-04-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0028_supportandresistence'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradayFutureAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_time', models.TimeField(auto_now=True)),
                ('today_date', models.DateField(auto_now=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('last_price', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('price_change', models.CharField(blank=True, max_length=100, null=True)),
                ('oi_change', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
