# Generated by Django 4.0.1 on 2022-04-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeniAnalysis_app', '0031_intradayfutureanalysis_oi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnfhistorylog',
            name='call_ltp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bnfhistorylog',
            name='call_oi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bnfhistorylog',
            name='put_ltp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bnfhistorylog',
            name='put_oi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historylog',
            name='call_ltp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historylog',
            name='call_oi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historylog',
            name='put_ltp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historylog',
            name='put_oi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
